//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSL_PRO_WEB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LSL_PRO_Entity : DbContext
    {
        public LSL_PRO_Entity()
            : base("name=LSL_PRO_Entity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LSL_PRO_Buttons> LSL_PRO_Button { get; set; }
        public virtual DbSet<LSL_PRO_DataRole> LSL_PRO_DataRole { get; set; }
        public virtual DbSet<LSL_PRO_LoginLog> LSL_PRO_LoginLog { get; set; }
        public virtual DbSet<LSL_PRO_Logs> LSL_PRO_Logs { get; set; }
        public virtual DbSet<LSL_PRO_Menus> LSL_PRO_Menu { get; set; }
        public virtual DbSet<LSL_PRO_MenuButtons> LSL_PRO_MenuButton { get; set; }
        public virtual DbSet<LSL_PRO_RoleMenus> LSL_PRO_RoleMenu { get; set; }
        public virtual DbSet<LSL_PRO_RoleMenuButtons> LSL_PRO_RoleMenuButton { get; set; }
        public virtual DbSet<LSL_PRO_Roless> LSL_PRO_Roles { get; set; }
        public virtual DbSet<LSL_PRO_Users> LSL_PRO_User { get; set; }
        public virtual DbSet<LSL_PRO_UserMenu> LSL_PRO_UserMenu { get; set; }
        public virtual DbSet<LSL_PRO_UserMenuButton> LSL_PRO_UserMenuButton { get; set; }
        public virtual DbSet<LSL_PRO_UserRoles> LSL_PRO_UserRole { get; set; }
    }
}
