//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSL_PRO_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSL_PRO_RoleMenuButtons
    {
        public string RoleMenuButtonId { get; set; }
        public string RoleId { get; set; }
        public string MenuId { get; set; }
        public string ButtonId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
    }
}
