//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSL_PRO_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSL_PRO_Users
    {
        public string UserId { get; set; }
        public string EmployeeId { get; set; }
        public string Code { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Secretkey { get; set; }
        public string RealName { get; set; }
        public string Spell { get; set; }
        public string Alias { get; set; }
        public string RoleId { get; set; }
        public string Gender { get; set; }
        public string Mobile { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Email { get; set; }
        public string OICQ { get; set; }
        public string DutyId { get; set; }
        public string TitleId { get; set; }
        public string OrganizationId { get; set; }
        public string CompanyId { get; set; }
        public string DepartmentId { get; set; }
        public string WorkgroupId { get; set; }
        public string Description { get; set; }
        public string SecurityLevel { get; set; }
        public Nullable<System.DateTime> ChangePasswordDate { get; set; }
        public Nullable<int> OpenId { get; set; }
        public string IPAddress { get; set; }
        public string MACAddress { get; set; }
        public Nullable<int> LogOnCount { get; set; }
        public Nullable<System.DateTime> FirstVisit { get; set; }
        public Nullable<System.DateTime> PreviousVisit { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public Nullable<int> Enabled { get; set; }
        public Nullable<int> SortCode { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
        public string SID { get; set; }
        public Nullable<int> IsFengKong { get; set; }
        public string UserType { get; set; }
        public Nullable<int> IsLogin { get; set; }
        public string IMAPServer { get; set; }
        public string SMTPServer { get; set; }
        public string EmailUserName { get; set; }
        public string EmailUserPassword { get; set; }
        public Nullable<int> SMTPPort { get; set; }
        public Nullable<int> IMAPPort { get; set; }
        public Nullable<int> IsSSL { get; set; }
        public string UserTypeGrade { get; set; }
    }
}
