//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSL_PRO_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSL_PRO_DataRole
    {
        public string DataRoleID { get; set; }
        public string RoleID { get; set; }
        public string DataType { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreatUserID { get; set; }
        public string CreatUserName { get; set; }
    }
}
