//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSL_PRO_WEB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LSL_PRO_Logs
    {
        public string SyslogsId { get; set; }
        public Nullable<int> OperationType { get; set; }
        public string TableName { get; set; }
        public string BusinessName { get; set; }
        public string Object_ID { get; set; }
        public string OperationIp { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public string Result { get; set; }
        public string OperationWhere { get; set; }
        public string Remark { get; set; }
    }
}
